apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-notebook
  labels:
    app: jupyter-notebook
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: jupyter-notebook
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jupyter-notebook
    spec:
      containers:
      - image: gcr.io/cloud-infra-project/jupyter/base-notebook:latest
        imagePullPolicy: Always
        name: base-notebook-1
        ports:
            - containerPort: 8888
