apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spark
  name: spark
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: spark
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spark
    spec:
      containers:
      - image: gcr.io/cloud-infra-project/bitnami/spark:latest
        imagePullPolicy: Always
        name: spark-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
